inherit_from:
  - .rubocop_todo.yml

Style/ClassAndModuleChildren:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/LineLength:
  Max: 393
  Exclude:
    - "spec/**/*"
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
AllCops:
  Exclude:
    - tmp/**/*