inherit_from:
  - .rubocop_todo.yml

Style/ClassAndModuleChildren:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - tmp/**/*