name: Ruby Rubocop Rspec
on: [push, pull_request]
jobs:
  build:
    name: Build + rubocop + rspec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          version: 2.6
      - name: Build
        run: |
          gem install bundler
          bundle install
      - name: rubocop
        run: bundle exec rubocop
      - name: rspec
        run: bundle exec rspec
